apiVersion: v1
kind: Service
metadata:
  namespace: spring-boot-examples
  name: spring-rest-students
spec:
  ports:
    - name: spring-rest-students
      port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    app: spring-rest-students
  type: ClusterIP